src/Entity/Camping.php
<?php

namespace App\Entity;

use App\Repository\CampingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CampingRepository::class)
 */
class Camping
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $logement;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;


    /**
     * @ORM\Column(type="text")
     */
    private $taille;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="camping")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogement(): ?string
    {
        return $this->logement;
    }

    public function setLogement(string $logement): self
    {
        $this->logement = $logement;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getTaille(): ?string
    {
        return $this->taille;
    }

    public function setTaille(string $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

}

templates/front/_annonce.html.twig
{% for camping in camping %}
<div class="row d-flex flex-row justify-content-center">
    <div class="card mb-2 ml-1 col-md-5">
        <div class="card_body">
            <img src="{{ asset('img/camping/'~camping.image) }}" class="card-img-top"/>
            <div class="card_title">{{ camping.logement }}</div>
            <div class="card_text">{{ camping.prix }} €</div>
            {% if camping.type == 1 %}
                <div class="card_text">Particulier</div>
            {% elseif camping.type == 2 %}
                <div class="card_text">Normal</div>
            {% else %}

            {% endif %}
            <a href="/annonceDetail/{{ camping.id }}"> Détails</a>
        </div>
    </div>
</div>
{% endfor %}

templates/front/_menu.html.twig
<nav>
    <ul>
        <li>
            <a href="/inscription">Inscription</a>
        </li>
        <li>
            <a href="/connection">Connection</a>
        </li>
    </ul>
</nav>

templates/front/accueil.html.twig
{% extends "base.html.twig" %}

{% block title %} Accueil {% endblock %}

{% block body %}
    <div class="jumbotron">
        <h1>Bienvenue sur la Page du Camping</h1>
    </div>
    <div>
        {{ include("front/_menu.html.twig") }}
    </div>
    <div>
        {{ include("front/_annonce.html.twig") }}
    </div>
    <div class="row d-flex flex-row justify-content-center">
        <div class="pagination">
            {{ knp_pagination_render(camping) }}
        </div>
    </div>

{% endblock %}

templates/front/detail.html.twig
{% extends "base.html.twig" %}
{% block title %}Annonce{{ detailCamping }} {% endblock %}

{% block body %}
    <a href="/accueil">Retour</a>
    <div class="row d-flex flex-row justify-content-center">
        <div class="card mb-2 ml-1 col-md-5">
            <div class="card_body">
                <img src="{{ asset('img/camping/'~camping.image) }}" class="card-img-top">
                <h2>{{ camping.logement }} n°{{ detailCamping }}</h2>
                <p>{{ camping.description }}</p>
                {% if camping.type == 1 %}
                    <div class="card_text">Particulier</div>
                {% elseif camping.type == 2 %}
                    <div class="card_text">Normal</div>
                {% else %}

                {% endif %}
                <div>{{ camping.prix }} €</div>
                {% if camping.logement == 'emplacement' %}
                <div>{{ camping.taille }}</div>
                {% else %}
                <div>{{ camping.taille }} place</div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/front/login-sign_up.html.twig
{% extends "base.html.twig" %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <h2 class="jumbotron">{{ title }}</h2>
    <a href="/accueil">Retour</a>
    <div class="container">
        <div class="card">
            <div class="card-body">
                {% if page == true %}
                    {% if error %}
                        <div class="alert alert-danger">{{ error.messageKey }}</div>
                    {% endif %}
                    <form method="post" action="{{ path('login') }}">
                    <div class="form-group">
                        <label for="username">Identifiant</label>
                        <input type="text" id="username" name="_username"
                               value="{{ last_username }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input id="password" name="_password"
                               type="password" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-default btn-outline-primary btn-sm">
                        Connection
                    </button>
                </form>
                {% else %}
                <div class="form-group">
                 {{ form_start(users) }}
                 {{ form_row(users.email) }}
                 {{ form_row(users.username) }}
                 {{ form_row(users.password) }}
                 {{ form_row(users.profil.prenom) }}
                 {{ form_row(users.profil.nom) }}
                 {{ form_row(users.profil.phone) }}
                    <br>
                 {{ form_row(users.button) }}
                 {{ form_rest(users) }}
                 {{ form_end(users) }}
                </div>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/front/reservation.html.twig
{% extends "base.html.twig" %}

{% block title %} {# Reservation(user)/Ses Location(proprio) #} {% endblock %}

{% block body %}

{% endblock %}